spring:
  application:
    name: processor
  elasticsearch:
    uris: //todo
    username: elastic
    password: elastic
  kafka:
    bootstrap-servers: //todo
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'


app:
  kafka:
    consumer:
      topic: repositories

